### PR TITLE
Setup Binary Exponentiation and KMP

### PR DESCRIPTION
**Pull request by CMoonBack**
I wrote the KMP algorithm and the Binary Exponentiation algorithm implementation, and modified the project structure a bit.

### CODE REVIEW

**Comment by Lampese** [comment]
did you use `moon fmt`?

**Review by Lampese — CHANGES_REQUESTED** [review]
.

**Comment by CMoonBack** [comment]
I see, I'm going to modify and re pull requests.

**Comment by CMoonBack** [comment]
I see, I'm going to modify and re pull requests.

**Pull request closed without merging**
